name: code_scanner
description: scanning qr code by camera & reading from qr code garrely image.
version: 1.0.0
homepage: "https://github.com/hondaya14/code_scanner"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: nqvno14.honhon.code_scanner
        pluginClass: CodeScannerPlugin
      ios:
        pluginClass: CodeScannerPlugin

